diff_drive_controller:
  ros__parameters:
    max_linear_velocity: 0.5      # m/s
    max_angular_velocity: 1     # rad/s
    cmd_vel_timeout: 0.5          # seconds
    publish_rate: 50.0            # Hz