A: {B: 2.0, C: 3.0, D: 4.0, E: 4.0, F: 2.5, G: 3.5}
B: {A: 2.0, C: 2.0, D: 3.0, E: 3.0, F: 2.0, G: 2.5}
C: {A: 3.0, B: 2.0, D: 2.0, E: 2.0, F: 2.5, G: 2.0}
D: {A: 4.0, B: 3.0, C: 2.0, E: 1.0, F: 3.5, G: 3.0}
E: {A: 4.0, B: 3.0, C: 2.0, D: 1.0, F: 3.5, G: 3.0}
F: {A: 2.5, B: 2.0, C: 2.5, D: 3.5, E: 3.5, G: 2.5}
G: {A: 3.5, B: 2.5, C: 2.0, D: 3.0, E: 3.0, F: 2.5}
